spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/animaldoctor24?useSSL=false
    username: jnb
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#  logging:
#    level:
#      com:
#        jnb:
#          animaldoctor24.domain: debug
#      root: info
jwt:
#  header: Authorization
  secret: YTlzbDc4azV6eTN0cTJkeWt0MTNzbGRneHZtb2wzYmViZHJoeXNocmNlMHB0bHZiNzV5eDJ0bTQ5cGRtY2Y5em1mcTJwOTh5YzZ3dnllam10anlkZmV4NXIyM3MwbzVkdXl6cjZ2bmF2czhwOXg4c2podXE1Y3U5YXphY2ljaDc=
#  access-token-validity-in-seconds: 600 # 10 min


# swagger home
# localhost:8080/swagger-ui.html