spring:
  datasource:
    hikari:
      validation-timeout: "10000"
      maxLifetime: "580000"
      username: jnb
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/animaldoctor24?useSSL=false
      connection-timeout: "10000"
      maximum-pool-size: "10"
      idleTimeout: "10000"
      connection-init-sql: SELECT 1 FROM DUAL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#mybatis:
#  configuration:
#    use-generated-keys: "true"
#    jdbc-type-for-null: "null"
#    lazy-load-trigger-methods: "false"
#    default-executor-type: reuse
#    cache-enabled: "false"
#    call-setters-on-nulls: "true"
  logging:
    level:
      com:
        jnb:
          animaldoctor24: debug
      root: info
  server:
    servlet:
      context-path: /
    port: "8080"
  jwt:
    header: Authorization
    secret: YTlzbDc4azV6eTN0cTJkeWt0MTNzbGRneHZtb2wzYmViZHJoeXNocmNlMHB0bHZiNzV5eDJ0bTQ5cGRtY2Y5em1mcTJwOTh5YzZ3dnllam10anlkZmV4NXIyM3MwbzVkdXl6cjZ2bmF2czhwOXg4c2podXE1Y3U5YXphY2ljaDc=
    access-token-validity-in-seconds: 600 # 10 min

