server:
  port: 8001
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.pib102.pibApp
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project
    username: "root"
    password: "1234"
    generate-unique-name: "false"
    hikari:
      maximum-pool-size: "4"
logging:
  level:
    "[com.pib102.pibApp]": debug
